#!/usr/bin/env bash

source "${HOME}/Singularis/bin/common"
source "${HOME}/Singularis/bin/variables"

log_info "Installing dwm"

log_info "Compiling dwm"
cd "${CONFIG}/dwm/dwm-config" || exit
sudo make clean install

log_info "Compiling dwm statusbar"
cd "${CONFIG}/dwm/dwm-statusbar" || exit
sudo make clean install
